version: '3.7'

services:
  app:
    image: ${PLUGIN_PIPELINE_SERVICE_IMAGE_NAME}:${PLUGIN_PIPELINE_SERVICE_IMAGE_VERSION}
    container_name: ${PLUGIN_PIPELINE_SERVICE_INSTANCE_NAME}
    environment:
      # plugin
      PIPELINE_CORE_NAME: ${PLUGIN_NAME}
      PIPELINE_CORE_VERSION: ${PLUGIN_VERSION}
      PIPELINE_CORE_DESCRIPTION: ${PLUGIN_DESCRIPTION}
      # service
      PIPELINE_SERVICE_DIR: ${PLUGIN_PIPELINE_SERVICE_DIR}
      PIPELINE_SERVICE_ENV_FILE: ${PLUGIN_PIPELINE_SERVICE_ENV_FILE}
      PIPELINE_SERVICE_IMAGE_NAME: ${PLUGIN_PIPELINE_SERVICE_IMAGE_NAME}
      PIPELINE_SERVICE_IMAGE_VERSION: ${PLUGIN_PIPELINE_SERVICE_IMAGE_VERSION}
      PIPELINE_SERVICE_IMAGE_AUTHOR: ${PLUGIN_PIPELINE_SERVICE_IMAGE_AUTHOR}
      PIPELINE_SERVICE_INSTANCE_NAME: ${PLUGIN_PIPELINE_SERVICE_INSTANCE_NAME}
      PIPELINE_SERVICE_INSTANCE_UUID: ${PLUGIN_PIPELINE_SERVICE_INSTANCE_UUID}
    env_file:
      - ${PLUGIN_PIPELINE_SERVICE_ENV_FILE}
    # volumes:
    #   - ${PLUGIN_PIPELINE_CONTEXT}:${PLUGIN_PIPELINE_WORKDIR}

networks:
  default:
    external: true
    name: ${PLUGIN_PIPELINE_NETWORK}
